# Site settings
title: Fabien Le Frapper, dev fullstack freelance
tag_text: Fabienheureux
description: Freelance full stack web developper, working & living in Paris, currently unavailable for work

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
