base_url = "https://fabien.cool"
default_language = "fr"
compile_sass = false
build_search_index = false
generate_robots_txt = true
generate_sitemap = true

[extra]
title = "Fabien Le Frapper"
description = "Bonjour 🎈. This is my personal website. Code, Wagtail, Django, Python, JavaScript."
author = "Fabien Le Frapper"

[markdown]
highlight_code = true
smart_punctuation = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[languages.en]
generate_feeds = false
build_search_index = false
