on: push
name: Build & deploy
jobs:
  build:
    name: Deploy fabien.cool
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: taiki-e/install-action@v2
      with:
        tool: zola@0.17.2
    - name: Build
      run: zola build
    - name: Install AWS CLI
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@master
    - run: aws s3 sync --endpoint-url https://garage.deuxfleurs.fr ./public/ s3://fabien.cool
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
