on: push
name: Build & deploy
jobs:
  build:
    name: Deploy fabien.cool
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Zola deploy
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        BUILD_DIR: .
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
